# fly.toml app configuration file generated for 2024-vintube on 2024-04-18T15:57:33+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '2024-vintube'
primary_region = 'sin'

[build]

app = "2024-vintube"
primary_region = "sin"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
